# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moolen/projekte/opengl/HRTFVR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moolen/projekte/opengl/HRTFVR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moolen/projekte/opengl/HRTFVR/CMakeFiles /home/moolen/projekte/opengl/HRTFVR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moolen/projekte/opengl/HRTFVR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myapp

# Build rule for target.
myapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myapp
.PHONY : myapp

# fast build rule for target.
myapp/fast:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/build
.PHONY : myapp/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/CubeTexture.o: src/CubeTexture.cpp.o
.PHONY : src/CubeTexture.o

# target to build an object file
src/CubeTexture.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/CubeTexture.cpp.o
.PHONY : src/CubeTexture.cpp.o

src/CubeTexture.i: src/CubeTexture.cpp.i
.PHONY : src/CubeTexture.i

# target to preprocess a source file
src/CubeTexture.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/CubeTexture.cpp.i
.PHONY : src/CubeTexture.cpp.i

src/CubeTexture.s: src/CubeTexture.cpp.s
.PHONY : src/CubeTexture.s

# target to generate assembly for a file
src/CubeTexture.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/CubeTexture.cpp.s
.PHONY : src/CubeTexture.cpp.s

src/Display.o: src/Display.cpp.o
.PHONY : src/Display.o

# target to build an object file
src/Display.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Display.cpp.o
.PHONY : src/Display.cpp.o

src/Display.i: src/Display.cpp.i
.PHONY : src/Display.i

# target to preprocess a source file
src/Display.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Display.cpp.i
.PHONY : src/Display.cpp.i

src/Display.s: src/Display.cpp.s
.PHONY : src/Display.s

# target to generate assembly for a file
src/Display.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Display.cpp.s
.PHONY : src/Display.cpp.s

src/Entity.o: src/Entity.cpp.o
.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/EntitySettings.o: src/EntitySettings.cpp.o
.PHONY : src/EntitySettings.o

# target to build an object file
src/EntitySettings.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/EntitySettings.cpp.o
.PHONY : src/EntitySettings.cpp.o

src/EntitySettings.i: src/EntitySettings.cpp.i
.PHONY : src/EntitySettings.i

# target to preprocess a source file
src/EntitySettings.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/EntitySettings.cpp.i
.PHONY : src/EntitySettings.cpp.i

src/EntitySettings.s: src/EntitySettings.cpp.s
.PHONY : src/EntitySettings.s

# target to generate assembly for a file
src/EntitySettings.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/EntitySettings.cpp.s
.PHONY : src/EntitySettings.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Loader.o: src/Loader.cpp.o
.PHONY : src/Loader.o

# target to build an object file
src/Loader.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Loader.cpp.o
.PHONY : src/Loader.cpp.o

src/Loader.i: src/Loader.cpp.i
.PHONY : src/Loader.i

# target to preprocess a source file
src/Loader.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Loader.cpp.i
.PHONY : src/Loader.cpp.i

src/Loader.s: src/Loader.cpp.s
.PHONY : src/Loader.s

# target to generate assembly for a file
src/Loader.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Loader.cpp.s
.PHONY : src/Loader.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/ShaderFactory.o: src/ShaderFactory.cpp.o
.PHONY : src/ShaderFactory.o

# target to build an object file
src/ShaderFactory.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/ShaderFactory.cpp.o
.PHONY : src/ShaderFactory.cpp.o

src/ShaderFactory.i: src/ShaderFactory.cpp.i
.PHONY : src/ShaderFactory.i

# target to preprocess a source file
src/ShaderFactory.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/ShaderFactory.cpp.i
.PHONY : src/ShaderFactory.cpp.i

src/ShaderFactory.s: src/ShaderFactory.cpp.s
.PHONY : src/ShaderFactory.s

# target to generate assembly for a file
src/ShaderFactory.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/ShaderFactory.cpp.s
.PHONY : src/ShaderFactory.cpp.s

src/SkyboxEntity.o: src/SkyboxEntity.cpp.o
.PHONY : src/SkyboxEntity.o

# target to build an object file
src/SkyboxEntity.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/SkyboxEntity.cpp.o
.PHONY : src/SkyboxEntity.cpp.o

src/SkyboxEntity.i: src/SkyboxEntity.cpp.i
.PHONY : src/SkyboxEntity.i

# target to preprocess a source file
src/SkyboxEntity.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/SkyboxEntity.cpp.i
.PHONY : src/SkyboxEntity.cpp.i

src/SkyboxEntity.s: src/SkyboxEntity.cpp.s
.PHONY : src/SkyboxEntity.s

# target to generate assembly for a file
src/SkyboxEntity.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/SkyboxEntity.cpp.s
.PHONY : src/SkyboxEntity.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Transform.o: src/Transform.cpp.o
.PHONY : src/Transform.o

# target to build an object file
src/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Transform.cpp.o
.PHONY : src/Transform.cpp.o

src/Transform.i: src/Transform.cpp.i
.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s
.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/obj_loader.o: src/obj_loader.cpp.o
.PHONY : src/obj_loader.o

# target to build an object file
src/obj_loader.cpp.o:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/obj_loader.cpp.o
.PHONY : src/obj_loader.cpp.o

src/obj_loader.i: src/obj_loader.cpp.i
.PHONY : src/obj_loader.i

# target to preprocess a source file
src/obj_loader.cpp.i:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/obj_loader.cpp.i
.PHONY : src/obj_loader.cpp.i

src/obj_loader.s: src/obj_loader.cpp.s
.PHONY : src/obj_loader.s

# target to generate assembly for a file
src/obj_loader.cpp.s:
	$(MAKE) -f CMakeFiles/myapp.dir/build.make CMakeFiles/myapp.dir/src/obj_loader.cpp.s
.PHONY : src/obj_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... myapp"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/CubeTexture.o"
	@echo "... src/CubeTexture.i"
	@echo "... src/CubeTexture.s"
	@echo "... src/Display.o"
	@echo "... src/Display.i"
	@echo "... src/Display.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/EntitySettings.o"
	@echo "... src/EntitySettings.i"
	@echo "... src/EntitySettings.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Loader.o"
	@echo "... src/Loader.i"
	@echo "... src/Loader.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/ShaderFactory.o"
	@echo "... src/ShaderFactory.i"
	@echo "... src/ShaderFactory.s"
	@echo "... src/SkyboxEntity.o"
	@echo "... src/SkyboxEntity.i"
	@echo "... src/SkyboxEntity.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/Transform.o"
	@echo "... src/Transform.i"
	@echo "... src/Transform.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/obj_loader.o"
	@echo "... src/obj_loader.i"
	@echo "... src/obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

